SELECT
    KONTRAK_NO AS "KONTRAK NO",
    'SUGUS' AS "CLIENT NAME",
    SUM(ANGSURAN_PER_BULAN) AS "TOTAL ANGSURAN BELUM TERBAYAR",
    SUM(ANGSURAN_PER_BULAN * 0.001 * DATEDIFF('2024-08-14', TANGGAL_JATUH_TEMPO)) AS "TOTAL DENDA"
FROM
    JADWAL_ANGSURAN
WHERE
    KONTRAK_NO = 'AGR00001'
    AND TANGGAL_JATUH_TEMPO BETWEEN '2024-05-01' AND '2024-08-14';
